server:
  port: 8761

spring:
  application:
    name: ead-service-registry

ead:
  serviceRegistry:
    username: serviceregistry
    password: '123456sr'

eureka:
  client:
    registerWithEureka: false #Não quer que seja cliente, mas sim servidor
    fetchRegistry: false
    service-url:
      defaultZone: 'http://${ead.serviceRegistry.username}:${ead.serviceRegistry.password}@localhost:8761/eureka'