spring:
  application:
    name: ead-authuser-service
  config:
    import: 'optional:configserver:' # optional:configserver - Quando o config-sever sair do ar e usar a configuração local
  cloud:
    config:
      discovery:
        serviceId: ead-config-server
