server:
  port: 8087

spring:
  application:
    name: ead-authuser-service
  datasource:
    url: jdbc:postgresql://localhost:5432/ead-authuser
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver  # Defina explicitamente o driver
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
  output:
    ansi:
      enabled: Always

logging:
  level:
    com.ead: TRACE
    root: INFO #Envolve todas as classes que tem o framework
    org.springframework.web: DEBUG # Para ver detalhes de uma requisição
    org.hibernate: INFO

ead:
  api:
    url:
      course: 'http://localhost:8082'

eureka:
  client:
    service-url:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost