server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ead-courser
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver  # Defina explicitamente o driver
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgresSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true

logging:
  level:
    com.ead: TRACE
    root: INFO #Envolve todas as classes que tem o framework
    org.springframework.web: DEBUG # Para ver detalhes de uma requisição
    org.hibernate: INFO

ead:
  api:
    url:
      authuser: 'http://localhost:8087'
