server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ead-courser
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver  # Defina explicitamente o driver
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
